repos:
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        types: [python]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        types: [python]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude: "tests/"
      - id: end-of-file-fixer
        exclude: "tests/"

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.7.0
    hooks:
      - id: pyupgrade
        args: [--py38-plus]
        types: [python]

  - repo: https://github.com/boidolr/pre-commit-images
    rev: v1.2.1
    hooks:
      - id: optimize-avif
        exclude: "tests/"
      - id: optimize-jpg
        exclude: "tests/"
      - id: optimize-png
        exclude: "tests/"
      - id: optimize-svg
        exclude: "tests/"
      - id: optimize-webp
        exclude: "tests/"
